"""create_tables

Revision ID: 80ff1947312d
Revises: 5e4e3e8b70dc
Create Date: 2025-11-28 12:02:16.696238

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '80ff1947312d'
down_revision: Union[str, Sequence[str], None] = '5e4e3e8b70dc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('medication',
    sa.Column('anvisa_code', sa.String(length=13), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=200), nullable=False),
    sa.PrimaryKeyConstraint('anvisa_code')
    )
    op.create_table('specialty',
    sa.Column('code', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('code')
    )
    op.create_table('ubs',
    sa.Column('cnes', sa.String(length=7), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('addres', sa.String(length=200), nullable=False),
    sa.PrimaryKeyConstraint('cnes')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('cpf', sa.String(length=11), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('phone_number', sa.String(length=11), nullable=False),
    sa.Column('birthdate', sa.Date(), nullable=False),
    sa.Column('email', sa.String(length=254), nullable=False),
    sa.Column('password', sa.String(length=64), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cpf')
    )
    op.create_table('doctor',
    sa.Column('cpf', sa.String(length=11), nullable=False),
    sa.Column('crm', sa.String(length=10), nullable=False),
    sa.ForeignKeyConstraint(['cpf'], ['user.cpf'], ),
    sa.PrimaryKeyConstraint('cpf'),
    sa.UniqueConstraint('crm')
    )
    op.create_table('nurse',
    sa.Column('cpf', sa.String(length=11), nullable=False),
    sa.Column('coren', sa.String(length=9), nullable=False),
    sa.ForeignKeyConstraint(['cpf'], ['user.cpf'], ),
    sa.PrimaryKeyConstraint('cpf'),
    sa.UniqueConstraint('coren')
    )
    op.create_table('patient',
    sa.Column('cpf', sa.String(length=11), nullable=False),
    sa.ForeignKeyConstraint(['cpf'], ['user.cpf'], ),
    sa.PrimaryKeyConstraint('cpf')
    )
    op.create_table('appointment',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('doctor_cpf', sa.String(length=11), nullable=False),
    sa.Column('patient_cpf', sa.String(length=11), nullable=False),
    sa.Column('ubs_cnes', sa.String(length=7), nullable=False),
    sa.Column('appointment_datetime', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['doctor_cpf'], ['doctor.cpf'], ),
    sa.ForeignKeyConstraint(['patient_cpf'], ['patient.cpf'], ),
    sa.ForeignKeyConstraint(['ubs_cnes'], ['ubs.cnes'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('doctor_specialty',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('doctor_cpf', sa.String(length=11), nullable=False),
    sa.Column('specialty_code', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['doctor_cpf'], ['doctor.cpf'], ),
    sa.ForeignKeyConstraint(['specialty_code'], ['specialty.code'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('doctor_ubs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('doctor_cpf', sa.String(length=11), nullable=False),
    sa.Column('ubs_cnes', sa.String(length=7), nullable=False),
    sa.ForeignKeyConstraint(['doctor_cpf'], ['doctor.cpf'], ),
    sa.ForeignKeyConstraint(['ubs_cnes'], ['ubs.cnes'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('nurse_specialty',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nurse_cpf', sa.String(length=11), nullable=False),
    sa.Column('specialty_code', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['nurse_cpf'], ['nurse.cpf'], ),
    sa.ForeignKeyConstraint(['specialty_code'], ['specialty.code'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('nurse_ubs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nurse_cpf', sa.String(length=11), nullable=False),
    sa.Column('ubs_cnes', sa.String(length=7), nullable=False),
    sa.ForeignKeyConstraint(['nurse_cpf'], ['nurse.cpf'], ),
    sa.ForeignKeyConstraint(['ubs_cnes'], ['ubs.cnes'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('patient_ubs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('patient_cpf', sa.String(length=11), nullable=False),
    sa.Column('ubs_cnes', sa.String(length=7), nullable=False),
    sa.ForeignKeyConstraint(['patient_cpf'], ['patient.cpf'], ),
    sa.ForeignKeyConstraint(['ubs_cnes'], ['ubs.cnes'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('vaccine',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('patient_cpf', sa.String(length=11), nullable=False),
    sa.Column('nurse_cpf', sa.String(length=11), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=200), nullable=False),
    sa.Column('manufacturer', sa.String(length=100), nullable=False),
    sa.ForeignKeyConstraint(['nurse_cpf'], ['nurse.cpf'], ),
    sa.ForeignKeyConstraint(['patient_cpf'], ['patient.cpf'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('exam',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('appointment_id', sa.Integer(), nullable=False),
    sa.Column('exam_date', sa.Date(), nullable=False),
    sa.Column('exam_type', sa.String(length=200), nullable=False),
    sa.ForeignKeyConstraint(['appointment_id'], ['appointment.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('prescription',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('appointment_id', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(length=200), nullable=False),
    sa.ForeignKeyConstraint(['appointment_id'], ['appointment.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('medication_prescription',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('medication_code', sa.String(length=13), nullable=False),
    sa.Column('prescription_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['medication_code'], ['medication.anvisa_code'], ),
    sa.ForeignKeyConstraint(['prescription_id'], ['prescription.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('medication_prescription')
    op.drop_table('prescription')
    op.drop_table('exam')
    op.drop_table('vaccine')
    op.drop_table('patient_ubs')
    op.drop_table('nurse_ubs')
    op.drop_table('nurse_specialty')
    op.drop_table('doctor_ubs')
    op.drop_table('doctor_specialty')
    op.drop_table('appointment')
    op.drop_table('patient')
    op.drop_table('nurse')
    op.drop_table('doctor')
    op.drop_table('user')
    op.drop_table('ubs')
    op.drop_table('specialty')
    op.drop_table('medication')
    # ### end Alembic commands ###
